---
version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@5.1.1
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  Create-Stack-Cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/Network.yml --stack-name VPC-Subnets
            aws cloudformation deploy --template-file cloudformation/SecurityGroups.yml --stack-name SGsetting --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation deploy --template-file cloudformation/Resorces.yml --stack-name Resorcesetting --capabilities CAPABILITY_IAM
  
  Run-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:tGJ9rWUTnITMP9ng9e/4JKOtblNtpnjZ51KMBK4cxnU"
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-i ansible/inventory'    

workflows:
  version: 2
  Provisioning:
    jobs:
      - Create-Stack-Cloudformation
      - Run-ansible:
          requires:
            - Create-Stack-Cloudformation       

